import { projectsApi, getCachedProjectIcon, getCachedProjectName } from '../api/projects'
import { versionsApi } from '../api/versions'
import { gitApi } from '../api/git'
import { settingsApi } from '../api/settings'
import { templatesApi } from '../api/templates'
import { categoriesApi } from '../api/categories'
import { workspacesApi } from '../api/workspaces'
import { changelogApi } from '../api/changelog'
import { newsApi } from '../api/news'
import { assetLibraryApi } from '../api/assetLibrary'

export { getCachedProjectIcon, getCachedProjectName }

export const api = {
  listProjects: projectsApi.list,
  createProject: projectsApi.create,
  importProject: projectsApi.import,
  removeProject: projectsApi.remove,
  updateProject: projectsApi.update,
  reorderProjects: projectsApi.reorder,
  saveProjectTags: projectsApi.saveTags,
  openProject: projectsApi.open,
  stopProject: projectsApi.stop,
  openProjectFolder: projectsApi.openFolder,
  openInEditor: projectsApi.openInEditor,
  getProjectSize: projectsApi.getSize,
  pickFolder: projectsApi.pickFolder,
  pickFile: projectsApi.pickFile,
  readImageFile: projectsApi.readImageFile,
  getProjectIcon: projectsApi.getIcon,
  getProjectName: projectsApi.getName,
  reintroduceDismissedProjects: projectsApi.reintroduceDismissed,
  clearProjectIconCache: projectsApi.clearIconCache,
  clearProjectNameCache: projectsApi.clearNameCache,

  fetchAvailableGodotVersions: versionsApi.fetchAvailable,
  downloadGodotVersion: versionsApi.download,
  pauseDownload: versionsApi.pauseDownload,
  resumeDownload: versionsApi.resumeDownload,
  cancelDownload: versionsApi.cancelDownload,
  listInstalledGodotVersions: versionsApi.listInstalled,
  renameGodotVersion: versionsApi.rename,
  deleteGodotVersion: versionsApi.delete,
  openGodotVersion: versionsApi.open,
  testGithubToken: versionsApi.testGithubToken,
  getGithubRateLimit: versionsApi.getGithubRateLimit,
  scanForVersions: versionsApi.scan,
  importVersion: versionsApi.import,
  importVersionZip: versionsApi.importZip,
  validateGodotFolder: versionsApi.validateFolder,

  cloneRepo: gitApi.clone,
  getGitStatus: gitApi.status,
  batchGitStatus: gitApi.batchStatus,
  openTerminal: gitApi.openTerminal,
  gitPull: gitApi.pull,
  gitFetch: gitApi.fetch,
  gitPush: gitApi.push,
  gitPushForce: gitApi.pushForce,
  gitLog: gitApi.log,
  gitLogEntries: gitApi.logEntries,
  gitRemoteUrl: gitApi.remoteUrl,
  gitListBranches: gitApi.listBranches,
  gitSwitchBranch: gitApi.switchBranch,
  gitCreateBranch: gitApi.createBranch,
  gitDeleteBranch: gitApi.deleteBranch,
  gitStashPush: gitApi.stashPush,
  gitStashList: gitApi.stashList,
  gitStashApply: gitApi.stashApply,
  gitStashDrop: gitApi.stashDrop,
  gitChangedFiles: gitApi.changedFiles,
  gitDiscardChanges: gitApi.discardChanges,
  gitInit: gitApi.init,
  gitStageFile: gitApi.stageFile,
  gitUnstageFile: gitApi.unstageFile,
  gitCommit: gitApi.commit,
  gitSetRemote: gitApi.setRemote,
  gitRemoveRemote: gitApi.removeRemote,
  gitFileDiff: gitApi.fileDiff,
  gitUndoCommit: gitApi.undoCommit,
  gitUndoPull: gitApi.undoPull,
  gitMergeConflictFiles: gitApi.mergeConflictFiles,
  gitResolveConflictOurs: gitApi.resolveConflictOurs,
  gitResolveConflictTheirs: gitApi.resolveConflictTheirs,
  gitResolveConflictManual: gitApi.resolveConflictManual,
  gitAbortMerge: gitApi.abortMerge,
  gitIsMerging: gitApi.isMerging,

  getSettings: settingsApi.get,
  updateSettings: settingsApi.update,
  resetSettings: settingsApi.reset,
  resetAppData: settingsApi.resetData,
  scanForProjects: settingsApi.scanForProjects,
  scanForProjectsWithInfo: settingsApi.scanForProjectsWithInfo,
  refreshTrayMenu: settingsApi.refreshTrayMenu,
  restartWatchers: settingsApi.restartWatchers,

  listTemplates: templatesApi.list,
  saveProjectAsTemplate: templatesApi.saveAsTemplate,
  deleteTemplate: templatesApi.delete,
  getTemplatePreview: templatesApi.getPreview,
  syncTemplatesWithScanDir: templatesApi.syncWithScanDir,

  listCategories: categoriesApi.list,
  createCategory: categoriesApi.create,
  renameCategory: categoriesApi.rename,
  updateCategory: categoriesApi.update,
  deleteCategory: categoriesApi.delete,
  reorderCategories: categoriesApi.reorder,

  listWorkspaces: workspacesApi.list,
  listWorkspaceScanDirs: workspacesApi.scanDirs,
  createWorkspace: workspacesApi.create,
  switchWorkspace: workspacesApi.switch,
  updateWorkspace: workspacesApi.update,
  deleteWorkspace: workspacesApi.delete,

  listChangelogEntries: changelogApi.list,
  addChangelogEntry: changelogApi.add,
  updateChangelogEntry: changelogApi.update,
  deleteChangelogEntry: changelogApi.delete,

  fetchGodotNews: newsApi.fetch,

  searchAssetLibrary: assetLibraryApi.search,
  installAssetAsTemplate: assetLibraryApi.installAsTemplate,
}
